"""The ``ts.v3`` catalog: TotalSegmentator v3's ``total_v3`` under v2's task names.

The registry (``data/ts_v3_tasks.json``) is generated by ``tools/gen_ts_registry.py`` from
TotalSegmentator 2.18.0's own source and checked there against the checkpoints. These tests
hold what must stay true of the shipped file without a network: the three tasks, the one
label that differs from v2, a union that paints every label once, and - the reason the
``models`` field exists - that every dataset states ``nnUNetPlans``, so a real install of
831-836 (which also ship the small ResEnc model) resolves to upstream's default.
"""
import json
import tempfile
import unittest
from pathlib import Path

from haversack.ecosystems import TS_V2_TASKS, TS_V3_TASKS, EcosystemCatalog, TSv3Ecosystem


def _tasks(path):
    return {t["name"]: t for t in json.loads(Path(path).read_text(encoding="utf-8"))["tasks"]}


class TheShippedRegistry(unittest.TestCase):
    def setUp(self):
        self.v2, self.v3 = _tasks(TS_V2_TASKS), _tasks(TS_V3_TASKS)

    def test_three_tasks_under_v2s_names(self):
        self.assertEqual(sorted(self.v3), ["total", "total_fast", "total_fastest"])
        self.assertEqual(sorted(TSv3Ecosystem().tasks()), sorted(self.v3))
        self.assertEqual({n: t["upstream"]["task"] for n, t in self.v3.items()},
                         dict.fromkeys(self.v3, "total_v3"))

    def test_the_datasets(self):
        self.assertEqual([p["weights_id"] for p in self.v3["total"]["union"]],
                         [831, 832, 833, 834, 835])
        self.assertEqual(self.v3["total_fast"]["single"], 836)
        self.assertEqual(self.v3["total_fastest"]["single"], 837)

    def test_labels_are_v2s_but_26_is_L6(self):
        for name, t in self.v3.items():
            old = self.v2[name]["label_map"]
            diff = {k: (old[k], t["label_map"][k]) for k in old if old[k] != t["label_map"].get(k)}
            self.assertEqual(diff, {"26": ("vertebrae_S1", "vertebrae_L6")}, name)
            self.assertEqual(set(t["label_map"]), set(old), name)

    def test_the_union_paints_every_label_exactly_once(self):
        painted = [v for p in self.v3["total"]["union"] for v in p["label_remap"].values()]
        self.assertEqual(sorted(painted), sorted(map(int, self.v3["total"]["label_map"])))

    def test_every_dataset_states_upstreams_default_plans(self):
        for name, t in self.v3.items():
            ids = [t["single"]] if t["shape"] == "single" else [p["weights_id"] for p in t["union"]]
            self.assertEqual(sorted(t["models"]), sorted(map(str, ids)), name)
            for wid in ids:
                self.assertEqual(t["models"][str(wid)]["plans"], "nnUNetPlans", (name, wid))
        self.assertEqual(self.v3["total"]["models"]["831"]["trainer"], "nnUNetTrainerNoMirroring")
        self.assertEqual(self.v3["total_fast"]["models"]["836"]["trainer"],
                         "nnUNetTrainer_4000epochs_NoMirroring")

    def test_the_label_listing_names_each_catalogs_own_registry(self):
        from haversack.ecosystems import TSEcosystem
        self.assertEqual(TSv3Ecosystem().label_listing("total", None, None)["source"],
                         {"file": "haversack/data/ts_v3_tasks.json"})
        self.assertEqual(TSEcosystem().label_listing("total", None, None)["source"],
                         {"file": "haversack/data/ts_tasks.json"})     # v2's record unmoved


class ARealInstallResolvesTheDefault(unittest.TestCase):
    """Dataset836 as v3.0.0-weights unpacks it: two 3d_fullres folders. Through the catalog,
    ``describe()`` - the result key's weights component - must read the default's sidecar."""

    def test_describe_reads_the_nnunetplans_folder(self):
        from haversack.segmenter import Segmenter
        from haversack.weights import WeightsStore
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            ds = root / "Dataset836_TotalSegmentator_total_3mm_1559subj"
            for plans in ("nnUNetPlans", "nnUNetResEncUNetLPlans_8"):
                f = ds / f"nnUNetTrainer_4000epochs_NoMirroring__{plans}__3d_fullres"
                (f / "fold_0").mkdir(parents=True)
                (f / "dataset.json").write_text(json.dumps({"channel_names": {"0": "CT"}}))
            # one sidecar for the dataset, where fetch_one writes it
            (ds / ".haversack-version.json").write_text(json.dumps({"tag": "v3.0.0-weights"}))
            seg = Segmenter(weights=WeightsStore(root, fetch=False),
                            catalog=EcosystemCatalog(root=root))
            d = seg.describe("ts.v3:total_fast")
            self.assertEqual([(e["id"], e.get("version"), e.get("model"))
                              for e in d["weights_installed"]],
                             [("836", "v3.0.0-weights",
                               "nnUNetTrainer_4000epochs_NoMirroring__nnUNetPlans__3d_fullres")])
            self.assertEqual(d["structures"][25], "vertebrae_L6")


if __name__ == "__main__":
    unittest.main()
